### ISSUE TITLE
Why so many semver-incompatible releases?

### ISSUE THREAD

**Issue by jplatte** [ctz/webpki-roots#20]
I was wondering why this crate so frequently has new semver-incompatible releases. Currently a project I work on depends on both 0.19.0 and 0.20.0, then I saw 0.21.0 is out now as well; I generally try to avoid duplicate versions of dependencies. It would be nice if new versions that only update `TLS_SERVER_ROOTS` entries but don't change the `webpki` version or otherwise have API-breaking changes could be patch releases (so 0.21.0 would have been 0.20.1).

**Comment by ctz** [comment]
I'll try to pay more attention to this in the future.
